### ISSUE TITLE
JRE not found

### ISSUE THREAD

**Issue by pdario** [moisescastellano/javadecompiler-tcplugin#1] opened 2021-12-31 13:38 UTC
Hello! I'm trying to use Java Decompiler plugin, but i always says JRE is not installed.
I have both JDK 17 and JRE 8 in my "Program Files\Java". What is missing?

**Comment by moisescastellano** [comment] 2022-01-02 15:24
Ciao Dario, thanks for reporting this issue:

### Short answer:

Add these 2 properties to the [JVM] section in the _**[TOTALCMD-INSTALL-DIR]/wcx/JavaDecompiler/tc_javaplugin.ini**_  file, changing the paths to your JRE install dir:
```
JVM_DLL=c:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
JVM_HOME=c:\Program Files\Java\jre1.8.0_311
```
Let me know if that works.

### Long answer:

The Java plugin interface searchs for the JRE in two ways:

1. In the Windows Registry, it searchs for the key **HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment**

	there it queries for "_JavaHome_" and "_RuntimeLib_", e.g.	my computer registry values:

		JavaHome		C:\Program Files\Java\jre1.8.0_311
		RuntimeLib		C:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
2. If those values do not exist, it searches for the config file:	**_[PLUGIN_DIR]/tc_javaplugin.ini_**

	in that file, in the [JVM] section, it searches for two properties:

		JVM_DLL=c:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
		JVM_HOME=c:\Program Files\Java\jre1.8.0_311

Oracle's (Sun) JDK and JRE installlables are executables that set those registry values. If your JRE installable was just a zip file and it did not set those registry values, this is an example of how _**tc_javaplugin.ini**_ can be configured:

```
[GENERAL]
LANGUAGE=EN

[JVM]
JAVA.OPTIONS=
JAVA.TC.JAVALIB=-Dtc.java.lib=%COMMANDER_PATH%/plugins/wcx/JavaDecompiler/javalib
JAVA.CLASS.PATH=-Djava.class.path=%COMMANDER_PATH%/plugins/wcx/JavaDecompiler/javalib/tc-classloader-2.2.jar
JVM_DLL=c:\Program Files\Java\jre1.8.0_311\bin\server\jvm.dll
JVM_HOME=c:\Program Files\Java\jre1.8.0_311

[WCX]
CLASS=moi.tcplugins.decompiler.Decompiler

```

Tha Java plugin interface and derived plugins were tested on **Oracle (Sun) JRE 1.8**  (jre-8u311-windows-x64.exe).
I've tried a few OpenJDKs versions and I'm getting an error "_Starting the Java Virtual Machine failed
. status =-6_". I am opening [new issues](https://github.com/moisescastellano/tcmd-java-plugin/issues/2) for that , also documenting all this in the [main README page](https://github.com/moisescastellano/javadecompiler-tcplugin).
Plese let me know if this works or does not work for you, and for which JREs/JDKs. 

Regards,
Moises

**Comment by pdario** [comment] 2022-01-03 10:37
Hello Moises!

Unfortunately, no luck!

This is the massage now:
[image: image.png]

Moreover, I installed JDK/JRE with Windows installer and the registry
entries are present:
[image: image.png]

Any idea?

**Comment by moisescastellano** [comment] 2022-01-03 20:53
Hi!

I cannot see the images showing the error msg.
Is your error "LoadLibrary Failed" or "Starting Java Virtual Machine failed"?
Yesterday I opened [this issue](https://github.com/moisescastellano/tcmd-java-plugin/issues/2) because the plugin is giving those errors with OpenJDK (also with a very specific Oracle JDK: jre-8u112.)

In that case, by now, recommendation is to install an Oracle (Sun) JDK/JRE version.

Otherwise, let me know what is your error message and which JRE are you using - also, I suppose your TCmd is 64 bits?

Regards
Moises

**Comment by pdario** [comment] 2022-01-04 09:17
Hello!

The error is "LoadLibrary Failed" and I have both JDK17 and JRE1.8 from
Oracle.
The error seems to point to the correct jvm.dll path; I have spaces in the
path ("Program Files").

**Comment by moisescastellano** [comment] 2022-01-04 11:02
Hi Dario:

Yes, I can reproduce the issue with JRE8_112: first it says "JRE is not installed" -in spite it is in the registry- then when the JVM_DLL and JVM_HOME are stablished it says "LoadLibrary Failed".

For the first one I will keep this issue open; for the second one I opened the other one at: https://github.com/moisescastellano/tcmd-java-plugin/issues/2

In the meanwhile, if you wanna give it a try, some working (Oracle JREs) versions are: jre1.8.0_211, jre-8u311-windows-x64

Regards
Moises

**Comment by moisescastellano** [comment] 2022-01-04 11:25
I am also discussing / asking for help with these issues at [this post in the TC forum](https://www.ghisler.ch/board/viewtopic.php?p=408889#p408889).

**Comment by pdario** [comment] 2022-01-04 12:40
Hello,

thanks for your reply, but I confirm the issue is presente with Oracle
jre1.8.0_311.

Dario

**Comment by moisescastellano** [comment] 2022-01-04 13:09
Hi, sorry to hear that,
maybe I missed something but I double checked in two computers that version works with this java plugin,
did you remove the JVM_DLL and JVM_HOME properties to previous JRE in tc_javaplugin.ini?
did you restarted TC after installing? 
is the registry now pointing to jre1.8.0_311? 

Moises

**Comment by pdario** [comment] 2022-01-04 13:34
I never changed JRE version, I always had jre1.8.0_311; I now removed the
entries in the ini file and now the error is: JRE is not installed.

The registry correctly points to the JRE.

Dario

**Comment by moisescastellano** [comment] 2022-01-04 14:09
OK. I will try to investigate further. At least I can replicate this error with the JRE1.8_112 version in my computer.
Thanks again for reporting

**Comment by pdario** [comment] 2022-01-04 14:10
Ok, I'll wait for your update then, thank you.

Dario

**Comment by NSP-0123456** [comment] 2022-01-06 06:55
If you want to bypass jdk search, you must install javalib folder inside %commanderpath% and then use JVM section to define:
JVM_DLL=
JVM_HOME=

32bit/64bit are not compatible only one choice is possible with current version. If you use total commander 64bit , the properties must point to 64bit JVM, 32bit plugin will fall in loadlibrary error. 
The best practice I.M.O. is to have a common javalib folder inside total commander installation folder and not duplicate for each plugin (except for debug purpose) 

java 1.8 remain the good choice developing  java17 plugin with additional modules need to be handled by additional jvm parameters but the current implementation is not yet prepared for it.

**Comment by moisescastellano** [comment] 2022-01-07 20:19
Hi Nsp:

Thanks for your post and email! While answering I've come to realize the reason for a couple errors I had in my plugins.
I am asking you what do you think about a couple modifications, please let me know!

> If you want to bypass jdk search, you must install javalib folder inside %commanderpath% and then use JVM section to define JVM_DLL= JVM_HOME=

That's correct, the exact jdk/jre search is, in this order:
1. inside %COMMANDER_PATH%/javalib/tc_javaplugin.ini, JVM section, variables JVM_DLL and JVM_HOME
2. in the Windows registry, key HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment
3. in the tc_javaplugin.ini of plugin directory (e.g. %commanderpath%\plugins\wcx\JavaDecompiler\tc_javaplugin.ini), JVM section, variables JVM_DLL and JVM_HOME

I think the third way should be in fact before the second, so in case the variables exist they override the Windows default JRE configuration.
What do you think? 

>  If you use total commander 64bit , the properties must point to 64bit JVM, 32bit plugin will fall in loadlibrary error.

Yes, but in my tests I have been always using TC64bits and  JREs 64 bits, still some of them fail with "LoadLibrary Failed" or "Starting Java Virtual Machine failed", as detailed here: https://github.com/moisescastellano/tcmd-java-plugin/issues/2

However this could be the thing with Dario:
@Dario: I assumed you were using 64bits version for both TC and JREs, could you check it?

> The best practice I.M.O. is to have a common javalib folder inside total commander installation folder

I have been publishing the plugins with javalib inside, so that people only have to enter the zip and the usual TC plugin installation process takes charge of everything.
This implies javalib unzips under the plugin dir, not in the common folder.

In the old way (1.x) people had to: 1. un-tgz-ing the plugin,	2. installing it, 3. realizing it needs a javalib dir 4. searching for it in the web 5. un-tgz-ing and un-tar-ing javalib 6. manually copying it to tcmd dir
I think that is too much for the average user just giving a try to the plugins.
Providing javalib inside the plugin zip simplified the process a lot.

> It is very important that javalib is unique per totalcmd installation. Only one JVM.dll can be safely loaded per TC process to avoid crash

The fact that only one JVM.dll is loaded is guaranteed by the .cpp code: search for this comment in java.cpp: // check if JVM is already running.
That is not related to having one unique javalib dir.

Now, while answering you, I realized that there could be in fact a problem with multiple javalib dirs:
the PluginClassLoader creates one class loader instance for the javalib dir, and then another one per each plugin dir.
If there is more than one plugin, just the javalib of the first plugin is loaded.
I was getting some random errors, I have now realized the problem was happening depending on which plugin was loaded first - and therefore which javalib.

For me the best solution is:
- Removing the javalib dir from my plugins distributions. As jars are not shared, all of them should go into the plugin dir. A small modification to PluginClassLoader has to be done to avoid error if the javalib dir does not exist
- The only common jar is tc-classloader-2.x.jar - it is used the one pointed by the JAVA.CLASS.PATH variable in tc_javaplugin.ini - but this is also how it works now
- If any developer creating a plugin based on this code wants to depend on a %COMMANDER_PATH%/javalib existing, he can still do it, and the code will use it.

What do you think?

**Comment by NSP-0123456** [comment] 2022-01-08 07:37
Your conclusion seems to be to good ones for me.

Inside javalib, you can also add some common libraries like logging it is also a place to add native libraries in the ext or ext64 folder. This have to be explained by each plugin developer.  

What should be provided by Christian is the javalib. And each new java plugin provider should link to the official javalib. If not, you can also create a specific git repository for the DLL and the javalib. (all the common) The javalib installation can be done with a dummy wdx plugin that return some info from the JVM and turn on the mixed mode for wlx if per monitor dpi is enabled...

What could be provided as a Dev Helper for java plugin, is the the common dll and some script to prepare a folder structure and help to pack the plugin  with installer for TC.

**Comment by moisescastellano** [comment] 2022-01-08 10:31
Yes, there is the [git repository for the Java plugin interface](https://github.com/moisescastellano/tcmd-java-plugin), aimed to host all the common code. I will provide in a separate folder the last version of javalib, basically the pluginClassLoader. [Logging is disabled by default](https://github.com/moisescastellano/tcmd-java-plugin/blob/main/logging.md), but the SL4J API could be also there.

Regarding the Dev Helper I am thinking of a very basic plugin, maybe a new version of  Ken Handel's Hello World, or a new one.

**Comment by pdario** [comment] 2022-01-10 10:41
Hello! I was using TC 32Bit with JRE 64 bit! I switched to TC 64bit and now it works, thank you!

**Comment by moisescastellano** [comment] 2022-01-10 19:11
Hi! Great!
I think now we can now close this issue, but previously I will write a Troubleshooting guide with this  and other problems and solutions and I will link it here.
Thanks for reporting this issue!

**Comment by moisescastellano** [comment] 2022-01-13 18:36
I have now created a [Troubleshooting guide](https://moisescastellano.github.io/tcmd-java-plugin/troubleshooting) including this issue, so I will close it.

**Closed as completed by moisescastellano** 2022-01-13 18:36 UTC
